#!/bin/sh

SSHCMD="ssh -Tq -o ServerAliveInterval=5 \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    callhome@$hostname"

while true; do
    PORT=`$SSHCMD`
    if test 0${PORT} -gt 0; then
      $SSHCMD -vvv -NC -R "*:${PORT}:127.0.0.1:22"
    fi
  sleep 5
done

##Server authorization
cat .ssh/authorized_keys 
command="/bin/echo 10001",no-user-rc,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3...E+8J x@somehost
